//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto_3REntities1 : DbContext
    {
        public Proyecto_3REntities1()
            : base("name=Proyecto_3REntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gps_Distrito> Gps_Distrito { get; set; }
        public virtual DbSet<tbl_Aceesos_Evento> tbl_Aceesos_Evento { get; set; }
        public virtual DbSet<tbl_Cargo_Personal> tbl_Cargo_Personal { get; set; }
        public virtual DbSet<tbl_Configuracion_Zonas> tbl_Configuracion_Zonas { get; set; }
        public virtual DbSet<tbl_Definicion_Opciones> tbl_Definicion_Opciones { get; set; }
        public virtual DbSet<tbl_Distritos> tbl_Distritos { get; set; }
        public virtual DbSet<tbl_Empresas> tbl_Empresas { get; set; }
        public virtual DbSet<tbl_Empresas_Vehiculos> tbl_Empresas_Vehiculos { get; set; }
        public virtual DbSet<tbl_EstadoCelular> tbl_EstadoCelular { get; set; }
        public virtual DbSet<tbl_Estados> tbl_Estados { get; set; }
        public virtual DbSet<tbl_Evento> tbl_Evento { get; set; }
        public virtual DbSet<tbl_GrupoTabla_Cab> tbl_GrupoTabla_Cab { get; set; }
        public virtual DbSet<tbl_GrupoTabla_Det> tbl_GrupoTabla_Det { get; set; }
        public virtual DbSet<tbl_Iconos> tbl_Iconos { get; set; }
        public virtual DbSet<TBL_Operarios_RegistroGPS> TBL_Operarios_RegistroGPS { get; set; }
        public virtual DbSet<tbl_OrdenTrabajo_Det> tbl_OrdenTrabajo_Det { get; set; }
        public virtual DbSet<tbl_OrdenTrabajo_Foto> tbl_OrdenTrabajo_Foto { get; set; }
        public virtual DbSet<tbl_OrdenTrabajo_Reasignacion> tbl_OrdenTrabajo_Reasignacion { get; set; }
        public virtual DbSet<tbl_Parametro_Movil> tbl_Parametro_Movil { get; set; }
        public virtual DbSet<tbl_Perfil> tbl_Perfil { get; set; }
        public virtual DbSet<tbl_Perfil_Accesos> tbl_Perfil_Accesos { get; set; }
        public virtual DbSet<tbl_Personal> tbl_Personal { get; set; }
        public virtual DbSet<tbl_Precios> tbl_Precios { get; set; }
        public virtual DbSet<tbl_Servicios> tbl_Servicios { get; set; }
        public virtual DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
        public virtual DbSet<tbl_Usuarios_Servicios> tbl_Usuarios_Servicios { get; set; }
        public virtual DbSet<tbl_Zonas> tbl_Zonas { get; set; }
        public virtual DbSet<Versiones> Versiones { get; set; }
        public virtual DbSet<TempoESTADO> TempoESTADO { get; set; }
        public virtual DbSet<TempoGPS> TempoGPS { get; set; }
        public virtual DbSet<TempoOperario> TempoOperario { get; set; }
        public virtual DbSet<tbl_OrdenTrabajo_Cab> tbl_OrdenTrabajo_Cab { get; set; }
        public virtual DbSet<tbl_precio_material> tbl_precio_material { get; set; }
    }
}
