//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Definicion_Opciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Definicion_Opciones()
        {
            this.tbl_Aceesos_Evento = new HashSet<tbl_Aceesos_Evento>();
        }
    
        public int id_Opcion { get; set; }
        public string nombre_opcion { get; set; }
        public string url_opcion { get; set; }
        public Nullable<int> parentID { get; set; }
        public string nombreParentID { get; set; }
        public string urlImagen_Opcion { get; set; }
        public Nullable<int> orden_Opcion { get; set; }
        public Nullable<int> interface_Opcion { get; set; }
        public string TipoInterface { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Aceesos_Evento> tbl_Aceesos_Evento { get; set; }
    }
}
