//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Aceesos_Evento
    {
        public int id_Acceso_evento { get; set; }
        public Nullable<int> id_Opcion { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<int> id_Evento { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        public virtual tbl_Definicion_Opciones tbl_Definicion_Opciones { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
