//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Operarios_RegistroGPS
    {
        public int ID_Gps { get; set; }
        public Nullable<int> id_operario { get; set; }
        public string GPS_Latitud { get; set; }
        public string GPS_Longitud { get; set; }
        public Nullable<System.DateTime> fecha_GPD { get; set; }
        public Nullable<System.DateTime> fecha_Android { get; set; }
        public Nullable<System.DateTime> fecha_AgregaRegistro { get; set; }
    }
}
