//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Precios
    {
        public int id_Precio { get; set; }
        public Nullable<int> id_TipoOrdenTrabajo { get; set; }
        public Nullable<decimal> cubicaje { get; set; }
        public Nullable<decimal> cubicajeFinal { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_TipoPrecio { get; set; }
        public Nullable<int> id_TipoMaterial { get; set; }
    }
}
