//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrdenTrabajo_Cab
    {
        public int id_OT { get; set; }
        public Nullable<int> id_TipoOrdenTrabajo { get; set; }
        public Nullable<int> id_Servicios { get; set; }
        public string nroObraTD { get; set; }
        public string direccion_OT { get; set; }
        public Nullable<int> id_Distrito { get; set; }
        public string referencia_OT { get; set; }
        public string descripcion_OT { get; set; }
        public Nullable<System.DateTime> fechaAprobacion_OT { get; set; }
        public Nullable<System.DateTime> fechaAsignacion_OT { get; set; }
        public Nullable<System.DateTime> fechaEnvioMovil_OT { get; set; }
        public Nullable<System.DateTime> fechaRegistro_OT { get; set; }
        public Nullable<System.DateTime> fechaReasignacion_OT { get; set; }
        public Nullable<System.DateTime> fechaCancelacion_OT { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public Nullable<int> id_PersonalJefeCuadrilla { get; set; }
        public Nullable<int> id_OT_Origen { get; set; }
        public string obsReasignacion_OT { get; set; }
        public Nullable<int> id_MotivoPrioridad { get; set; }
        public string obsMotivoPrioridad_OT { get; set; }
        public string observaciones_OT { get; set; }
        public Nullable<int> ordenamiento_OT { get; set; }
        public string latitud_OT { get; set; }
        public string longitud_OT { get; set; }
        public Nullable<decimal> totalMedidas_OT { get; set; }
        public Nullable<decimal> totalDesmonteRecojido_OT { get; set; }
        public Nullable<decimal> totalDesmontePorRecojido_OT { get; set; }
        public Nullable<decimal> solesMedidas_OT { get; set; }
        public Nullable<decimal> solesDesmonteRecojido_OT { get; set; }
        public Nullable<decimal> solesDesmontePorRecojido_OT { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<int> id_distrito_GPS { get; set; }
        public string suminitroTD { get; set; }
        public string nroSed { get; set; }
        public Nullable<int> id_DistritoGps { get; set; }
        public string fotoPD_OT { get; set; }
        public string fotoTd_Origen { get; set; }
        public Nullable<int> usuario_aprueba { get; set; }
        public Nullable<int> viaje_indebido { get; set; }
        public string observacion { get; set; }
        public Nullable<int> usuario_recepcion { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<System.DateTime> fecha_RecepcionDB { get; set; }
        public Nullable<System.DateTime> fechaInicio_Trabajo { get; set; }
        public Nullable<System.DateTime> fechaTermino_Trabajo { get; set; }
        public Nullable<int> validacion { get; set; }
        public string nombreArchivo { get; set; }
        public string nombreArchivoServidor { get; set; }
        public string observacionGestor_OT { get; set; }
        public string estatus_OT { get; set; }
    }
}
