//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EstadoCelular
    {
        public int id_EstadoCelular { get; set; }
        public Nullable<int> id_Operario { get; set; }
        public Nullable<bool> GpsActivo { get; set; }
        public Nullable<int> estadoBateria { get; set; }
        public Nullable<System.DateTime> FechaHoraAndroid { get; set; }
        public Nullable<System.DateTime> FechaAgregaRegistro { get; set; }
        public Nullable<int> ModoAvion { get; set; }
        public Nullable<bool> PlanDatos { get; set; }
    }
}
