//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Estados
    {
        public int id_Estado { get; set; }
        public string abreviatura_estado { get; set; }
        public string descripcion_estado { get; set; }
        public string tipoproceso_estado { get; set; }
        public string descripcion_tipoproceso_estado { get; set; }
        public Nullable<int> id_Modulo { get; set; }
        public Nullable<int> orden_estado { get; set; }
        public string Backcolor_estado { get; set; }
        public string forecolor_estado { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string Simbolo_estado { get; set; }
        public string grupo_Estado { get; set; }
    }
}
