//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempoOperario
    {
        public int id_Operario { get; set; }
        public string nroDoc_Operario { get; set; }
        public string Apellidos_Operario { get; set; }
        public string nombre_Operario { get; set; }
        public string usuario_Operario { get; set; }
        public string contrasenia_Operario { get; set; }
    }
}
